server:
  port: 12345
spring:
  application:
    name: nacos-service-provider
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848

  user:
    id: 1
    name: 张三
    age: 22